### ISSUE TITLE
Images.xcassets以下にLINE.imagesetが自動的に生成されません。

### ISSUE THREAD

**Issue by emahiro** [anchan828/social-connector#12]
突然のご連絡失礼致します。

今けーごさんが作られたSocialConnectorを使ってUnityで開発しているゲームにSNSとの連携機能を実装しておりますが、READMEに書かれているようにLINEの画像を別途用意し、実際に実機で確認してみたところLINEの画像が反映されずにおります。
もともと用意されているダミーの画像も実機で確認できず、生成されたXcodeプロジェクトを確認したところ、Images.xcassets/LINE.imagesetが生成されておりませんでした。

開発環境は

・Unity4.6
・Xcode6.1

でビルドしております。
何卒よろしくお願いいたします。

**Comment by ememhr** [comment]
ご対応ありがとうございます！

**Comment by ememhr** [comment]
![20150105072030](https://cloud.githubusercontent.com/assets/8054136/5611949/c4f16a44-9510-11e4-845d-636d75abd1b7.png)

**Comment by anchan828** [comment]
チケットを分けました

#14 iOS7.1.2の端末にてクラッシュ

#15 LINE画像が縮小されて表示されてしまう
あれ、本当ですね。これ解決方法あるのかな...
