### ISSUE TITLE
LINE画像が縮小されて表示されてしまう

### ISSUE THREAD

**Issue by anchan828** [anchan828/social-connector#15]

**Comment by anchan828** [comment]
![](https://cloud.githubusercontent.com/assets/8054136/5611949/c4f16a44-9510-11e4-845d-636d75abd1b7.png)

**Comment by ememhr** [comment]
こちらチケット分けて頂きありがとうございます。

画像はiPhone6のもので、iPhone6+だと表示されませんでした。

宜しくお願い致します。

**Comment by anchan828** [comment]
iPhone6+ & iOS8では問題なし。
![ss 2015-01-12 14 10 16](https://cloud.githubusercontent.com/assets/694454/5699188/c71f90c6-9a64-11e4-9aef-908d61afc4ec.png)

**Comment by anchan828** [comment]
iPhone6 & iOS 8 ちょっと上ズレてる...
![ss 2015-01-12 14 32 02](https://cloud.githubusercontent.com/assets/694454/5699314/f027f816-9a67-11e4-9f04-9de00dcadf08.png)

iPhone5+ & iOS 7.1 問題なし

![ss 2015-01-12 14 32 20](https://cloud.githubusercontent.com/assets/694454/5699320/06c585de-9a68-11e4-837c-2cd5d618d25b.png)

**Comment by anchan828** [comment]
うーん

画像の解像度の問題かなぁーと思いましたが、上にずれている時点で何かがおかしいです...
このズレを治す方法が見つからない、特に致命的な問題では無いのでこのissueは寝かせてください。

@ememhr さんのスクショのLINE画像は周りに余白が無いですか？LINEが用意しているデフォルトのアイコンがそうなので...

**Comment by ememhr** [comment]
@anchan828 さん
こちら対応ありがとうございます。

ご指摘された点に関してですが、LINEの画像の周りに確かに余白ありました。
おそらくこれが原因で小さくなっていたものと思われます。

若干画像が上にずれている点ですが、アプリに影響はないので、このまま利用させていただきます。

ありがとうございました。
