### ISSUE TITLE
can not share both of image and text

### ISSUE THREAD

**Issue by fushang** [anchan828/social-connector#22]
Hi anchan828
I use this plugin and i see that, with sample "SocialConnector.Share("Social Connector", "https://github.com/anchan828/social-connector", imagePath);"
1. when I call this code, only image was showed. There are no text in the post.
2. when I remove imagePath, this code will share the link without "Social Connector".
I use v0.3.5 for my project (unity 4).
Can you show me how can I share both of image and link.

**Comment by anchan828** [comment]
Hi @fushang 

Could you tell me you're calling what the application for sharing? Facebook?

**Comment by fushang** [comment]
@anchan828 yes. I share to facebook

**Comment by anchan828** [comment]
we can't share the text :(

please read this facebook policy https://developers.facebook.com/docs/apps/review/prefill

**Comment by fushang** [comment]
i understood, thank for your support :)
